### PR TITLE
Ryan L. | adding Code of Conduct page

### PR DESCRIPTION
**Pull request by rlynn523**
Converted old COC html to markdown, created basic page template for markdown.
#1

### CODE REVIEW

**Comment by gilcreque** [comment]
@rlynn523 I made some adjustment to your PR to use the layout file. It looks like the version of Gatsby being used on the project may be too old for the Remark plugin because it is throwing an error on the CI. Can you take a look at this when you have a chance. Thanks!

**Comment by rlynn523** [comment]
@gilcreque sure thing!

**Comment by rlynn523** [comment]
@gilcreque how would you feel about updating all the gatsby packages? They seem to be pretty far behind latest

**Comment by gilcreque** [comment]
Hey @rlynn523, that sounds good. I haven't found a need to update before now. ✌️

**Pull request merged**
